### IMPORT LIBRARIES

In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
#Read updated scraped zipcode for cleaning
hdb_locations = pd.read_csv("updated_sg_zipcode_mapper_utfv2.csv", index_col=0)
hdb_locations.shape

(35293, 9)

### CLEANING OPERATION: zipcode file (hdb_locations)

In [3]:
hdb_locations

,postal,lat,lng,searchval,block,street_name,building,address,postal.1
0,398614,1.312763,103.883519,# 1 LOFT,1,LORONG 24 GEYLANG,# 1 LOFT,1 LORONG 24 GEYLANG # 1 LOFT SINGAPORE 398614,398614
1,398721,1.312390,103.881504,# 1 SUITES,1,LORONG 20 GEYLANG,# 1 SUITES,1 LORONG 20 GEYLANG # 1 SUITES SINGAPORE 398721,398721
2,629875,1.309135,103.679463,1 BENOI RD SINGAPORE 629875,1,BENOI RD,NIL,1 BENOI RD SINGAPORE 629875,629875
3,439731,1.305466,103.895674,1 BOSCOMBE RD SINGAPORE 439731,1,BOSCOMBE RD,NIL,1 BOSCOMBE RD SINGAPORE 439731,439731
4,659592,1.344619,103.749789,1 BUKIT BATOK ST 22 SINGAPORE 659592,1,BUKIT BATOK ST 22,NIL,1 BUKIT BATOK ST 22 SINGAPORE 659592,659592
...,...,...,...,...,...,...,...,...,...
35288,649406,1.347186,103.722687,YUHUA SECONDARY SCHOOL,35,JURONG WEST STREET 41,YUHUA SECONDARY SCHOOL,35 JURONG WEST STREET 41 YUHUA SECONDARY SCHOO...,649406
35289,529393,1.351292,103.950462,YUMIN PRIMARY SCHOOL,3,TAMPINES STREET 21,YUMIN PRIMARY SCHOOL,3 TAMPINES STREET 21 YUMIN PRIMARY SCHOOL SING...,529393
35290,658712,1.342339,103.760033,ST ANDREW'S MISSION SCHOOL,11,BUKIT BATOK STREET 25,ST ANDREW'S MISSION SCHOOL,11 BUKIT BATOK STREET 25 ST ANDREW'S MISSION S...,658712
35291,538884,1.357136,103.890195,YUYING SECONDARY SCHOOL,47,HOUGANG AVENUE 1,YUYING SECONDARY SCHOOL,47 HOUGANG AVENUE 1 YUYING SECONDARY SCHOOL SI...,538884
35292,556095,1.360261,103.869713,LEARNING STUDIO BY ZENITANT (ZHONGHUA PRIMARY ...,12,SERANGOON AVENUE 4,LEARNING STUDIO BY ZENITANT (ZHONGHUA PRIMARY ...,12 SERANGOON AVENUE 4 LEARNING STUDIO BY ZENIT...,556095

In [4]:
# duplicated geocode "BLK 216 AND 215 CHOA CHU KANG CENTRAL"
# Add one data row for BLK 215

hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('BLK 216 AND')] 

newrow = {'postal': '680216', 'lat': '1.3831978', 'lng': '103.7471233', 'searchval': 'HDB-CHOA CHU KANG',
          'block': '216','street_name': 'CHOA CHU KANG CTRL', 'building': 'HDB-CHOA CHU KANG',
          'address': '216 CHOA CHU KANG CTRL HDB-CHOA CHU KANG SINGAPORE 680216', 'postal.1': '680216'}

new_df = pd.DataFrame([newrow])

# Concatenate with the original DataFrame
hdb_locations = pd.concat([hdb_locations, new_df], ignore_index=True)

In [5]:
#### Pattern Matching Cleaning on hdb_locations ####
####################################################

# Replace 'AVENUE' with 'AVE' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('AVENUE', 'AVE')

# Replace 'NORTH' with 'NTH' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('NORTH', 'NTH')

# Replace 'ROAD' with 'RD' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('ROAD', 'RD')

# Replace 'STREET' with 'ST' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('STREET', 'ST')

# Replace 'JALAN' with 'JLN' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('JALAN', 'JLN')

# Replace 'PLACE' with 'PL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('PLACE', 'PL')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('CLOSE', 'CL')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('TANJONG', 'TG')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('MARKET', 'MKT')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('LORONG', 'LOR')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('CENTRAL', 'CTRL')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('BUKIT', 'BT')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('UPPER', 'UPP')
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('UPPERER', 'UPP')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('KAMPONG', 'KG')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('SAINT', 'ST.')

# Replace 'CLOSE' with 'CL' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('PARK', 'PK')

# Replace 'DRIVE' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('DRIVE', 'DR')

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('DRIVE', 'DR')

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('NTHSHORE', 'NORTHSHORE')

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('COMMONWEALTH', "C'WEALTH")

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('CRESCENT', "CRES")

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('GARDENS', "GDNS")

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('SOUTH', "STH")

# Replace 'DRIVR' with 'DR' in the 'street_name' column
hdb_locations['street_name'] = hdb_locations['street_name'].str.replace('TERRACE', "TER")

In [6]:
# Identify any duplicated block+streetname codes
duplicate_rows = hdb_locations[hdb_locations.duplicated(subset=['block', 'street_name'], keep=False)]
duplicate_rows

,postal,lat,lng,searchval,block,street_name,building,address,postal.1
86,467010,1.327276,103.924804,10 CHAI CHEE RD SINGAPORE 467010,10,CHAI CHEE RD,NIL,10 CHAI CHEE RD SINGAPORE 467010,467010
185,821103,1.398255,103.904754,103A EDGEFIELD PLAINS SINGAPORE 821103,103A,EDGEFIELD PLAINS,NIL,103A EDGEFIELD PLAINS SINGAPORE 821103,821103
186,822103,1.397731,103.904685,103B EDGEFIELD PLAINS SINGAPORE 822103,103B,EDGEFIELD PLAINS,NIL,103B EDGEFIELD PLAINS SINGAPORE 822103,822103
188,823103,1.397267,103.904538,103C EDGEFIELD PLAINS SINGAPORE 823103,103C,EDGEFIELD PLAINS,NIL,103C EDGEFIELD PLAINS SINGAPORE 823103,823103
191,821104,1.396806,103.905054,104A EDGEFIELD PLAINS SINGAPORE 821104,104A,EDGEFIELD PLAINS,NIL,104A EDGEFIELD PLAINS SINGAPORE 821104,821104
...,...,...,...,...,...,...,...,...,...
35212,227968,1.299365,103.848687,SCHOOL OF THE ARTS (SOTA),1,ZUBIR SAID DR,SCHOOL OF THE ARTS (SOTA),1 ZUBIR SAID DRIVE SCHOOL OF THE ARTS (SOTA) S...,227968
35219,309437,1.320807,103.827745,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190,DUNEARN RD,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190 DUNEARN ROAD SINGAPORE CHINESE GIRLS' SCHO...,309437
35220,309437,1.320807,103.827745,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190,DUNEARN RD,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190 DUNEARN ROAD SINGAPORE CHINESE GIRLS' SCHO...,309437
35237,387724,1.324361,103.881659,YMCA STUDENT CARE CENTRE @ ST MARGARET'S,2,MATTAR RD,YMCA STUDENT CARE CENTRE @ ST MARGARET'S,2 MATTAR ROAD YMCA STUDENT CARE CENTRE @ ST MA...,387724
35280,768675,1.424267,103.830032,YISHUN INNOVA JUNIOR COLLEGE,3,YISHUN RING RD,YISHUN INNOVA JUNIOR COLLEGE,3 YISHUN RING ROAD YISHUN INNOVA JUNIOR COLLEG...,768675

In [7]:
# Identify any duplicated geo codes
duplicate_geocode = hdb_locations[hdb_locations.duplicated(subset=['postal','lat', 'lng'], keep=False)]
duplicate_geocode

,postal,lat,lng,searchval,block,street_name,building,address,postal.1
86,467010,1.327276,103.924804,10 CHAI CHEE RD SINGAPORE 467010,10,CHAI CHEE RD,NIL,10 CHAI CHEE RD SINGAPORE 467010,467010
185,821103,1.398255,103.904754,103A EDGEFIELD PLAINS SINGAPORE 821103,103A,EDGEFIELD PLAINS,NIL,103A EDGEFIELD PLAINS SINGAPORE 821103,821103
186,822103,1.397731,103.904685,103B EDGEFIELD PLAINS SINGAPORE 822103,103B,EDGEFIELD PLAINS,NIL,103B EDGEFIELD PLAINS SINGAPORE 822103,822103
188,823103,1.397267,103.904538,103C EDGEFIELD PLAINS SINGAPORE 823103,103C,EDGEFIELD PLAINS,NIL,103C EDGEFIELD PLAINS SINGAPORE 823103,823103
191,821104,1.396806,103.905054,104A EDGEFIELD PLAINS SINGAPORE 821104,104A,EDGEFIELD PLAINS,NIL,104A EDGEFIELD PLAINS SINGAPORE 821104,821104
...,...,...,...,...,...,...,...,...,...
35147,599986,1.332948,103.783393,METHODIST GIRLS' SCHOOL,11,BLACKMORE DR,METHODIST GIRLS' SCHOOL,11 BLACKMORE DRIVE METHODIST GIRLS' SCHOOL SIN...,599986
35174,168622,1.286514,103.837127,OUTRAM SECONDARY SCHOOL,3,YORK HILL,OUTRAM SECONDARY SCHOOL,3 YORK HILL OUTRAM SECONDARY SCHOOL SINGAPORE ...,168622
35212,227968,1.299365,103.848687,SCHOOL OF THE ARTS (SOTA),1,ZUBIR SAID DR,SCHOOL OF THE ARTS (SOTA),1 ZUBIR SAID DRIVE SCHOOL OF THE ARTS (SOTA) S...,227968
35219,309437,1.320807,103.827745,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190,DUNEARN RD,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190 DUNEARN ROAD SINGAPORE CHINESE GIRLS' SCHO...,309437
35220,309437,1.320807,103.827745,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190,DUNEARN RD,SINGAPORE CHINESE GIRLS' SCHOOL (PRIMARY),190 DUNEARN ROAD SINGAPORE CHINESE GIRLS' SCHO...,309437

In [8]:
# Drop duplicated geolocations
hdb_locations = hdb_locations.drop_duplicates(subset=['block', 'street_name'])
hdb_locations = hdb_locations.drop_duplicates(subset=['postal.1','lat', 'lng'])

In [9]:
# Identify any duplicated postal codes
duplicate_postal = hdb_locations[hdb_locations.duplicated(subset=['postal.1'], keep=False)]
duplicate_postal

Empty DataFrame
Columns: [postal, lat, lng, searchval, block, street_name, building, address, postal.1]
Index: []

In [10]:
# Clean HDB locations dataset
cleaned_hdb_locations = hdb_locations.drop(['postal','address', 'searchval','building'], axis = 1)
cleaned_hdb_locations = cleaned_hdb_locations.drop_duplicates()

#Rename 'postal.1' column
cleaned_hdb_locations.rename(columns={'postal.1':'postal'},inplace=True)

In [11]:
cleaned_hdb_locations = cleaned_hdb_locations.reset_index(drop=True)
cleaned_hdb_locations

             lat          lng block         street_name  postal
0       1.312763   103.883519     1      LOR 24 GEYLANG  398614
1        1.31239   103.881504     1      LOR 20 GEYLANG  398721
2       1.309135   103.679463     1            BENOI RD  629875
3       1.305466   103.895674     1         BOSCOMBE RD  439731
4       1.344619   103.749789     1      BT BATOK ST 22  659592
...          ...          ...   ...                 ...     ...
26098   1.351292   103.950462     3      TAMPINES ST 21  529393
26099   1.342339   103.760033    11      BT BATOK ST 25  658712
26100   1.357136   103.890195    47       HOUGANG AVE 1  538884
26101   1.360261   103.869713    12     SERANGOON AVE 4  556095
26102  1.3831978  103.7471233   216  CHOA CHU KANG CTRL  680216

[26103 rows x 5 columns]

### Finalised hdb_locations as "cleaned_sg_zipcode_mapper_utfv2"

In [12]:
#cleaned_hdb_locations.to_csv("cleaned_sg_zipcode_mapper_utf.csv")

### ARCHIVED

In [13]:
"""hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('NEIGHBOURHOOD')]
#hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('PCF SPARKLETOTS PRESCHOOL')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('STUDENT CARE')]
#hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('DBS')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('UOB')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('OCBC')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('RESEARCH')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('SHOPPING')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('DEVELOPMENT')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('BANK OF')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains(' SCHOOL')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('ACADEMY')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('SERVICE')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('CHILD CARE')]
hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('SKOOL')]"""

"hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('NEIGHBOURHOOD')]\n#hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('PCF SPARKLETOTS PRESCHOOL')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('STUDENT CARE')]\n#hdb_locations = hdb_locations[~hdb_locations['building'].str.contains('DBS')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('UOB')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('OCBC')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('RESEARCH')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('SHOPPING')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('DEVELOPMENT')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('BANK OF')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains(' SCHOOL')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('ACADEMY')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('SERVICE')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('CHILD CARE')]\nhdb_locations = hdb_locations[~hdb_locations['building'].str.contains('SKOOL')]"